name: Carthage

on: [push]

jobs:
  carthage:
    name: "Xcode ${{ matrix.env.xcode }}"
    runs-on: macOS-12
    strategy:
      matrix:
        env:
          - xcode: 13.4
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "Upgrade Carthage"
        run: brew upgrade carthage
      - name: "Select Xcode ${{ matrix.env.xcode }}"
        uses: ./.github/actions/xcode-select
        with:
          version: ${{ matrix.env.xcode }}
      - name: "Build"
        run: carthage build --no-skip-current --use-xcframeworks --no-use-binaries
