name: SPM

on: [push]

jobs:
  spm:
    name: "Xcode ${{ matrix.env.xcode }}"
    runs-on: macOS-12
    strategy:
      matrix:
        env:
          - xcode: 13.4
    steps:
      - uses: actions/checkout@v3
      - name: "Select Xcode ${{ matrix.env.xcode }}"
        uses: ./.github/actions/xcode-select
        with:
          version: ${{ matrix.env.xcode }}
      - run: swift test
